<?xml version="1.0"?>
<!--Author: Victor Covasan-->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="arm">
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="plateLength" value="0.180"/>
  <xacro:property name="plateWidth" value="0.25"/>
  <xacro:property name="plateMass" value="0.267"/>
  <xacro:property name="plateHeight" value="0.006"/>
  <xacro:property name="baseHeight" value="0.0635"/>
  <xacro:property name="baseRadius" value="0.12"/>
  <xacro:property name="motor2Length" value="0.36"/>
  <xacro:property name="motor3Length" value="0.5"/>
  <xacro:property name="chassisWidth" value="0.45"/>
  <xacro:property name="baseDamping" value="0.1"/>
  <xacro:property name="sidePlateLenght" value="0.25"/>
  <xacro:property name="sidePlateWidth" value="0.05"/>
  <xacro:property name="sidePlateHeight" value="0.165"/>
  <xacro:property name="motor2Length" value="0.36"/>
  <xacro:property name="motor2Radius" value="0.08"/>
  <xacro:property name="sidePlate2Motor2Damping" value="0.1"/>
  <xacro:property name="motor3Length" value="0.5"/>
  <xacro:property name="motor3Radius" value="0.05"/>
  <xacro:property name="excavatorLenght" value="0.005"/>
  <xacro:property name="excavatorWidth" value="0.078"/>
  <xacro:property name="excavatorHeight" value="0.078"/>

  <!--link name="plate"> <visual> <origin xyz="0 0 0" rpy="0 0 0"/> <geometry> <box size="${plateLength} ${plateWidth} ${plateHeight}"/> </geometry> <material name="black"> <color rgba="0.5 0.0 0.0 1"/> </material> </visual> <collision> <origin xyz="0
  0 0" rpy="0 0 0"/> <geometry> <box size="${plateLength} ${plateWidth} ${plateHeight}"/> </geometry> </collision> <inertial> <origin xyz="0 0 ${plateHeight/2}" rpy="0 0 0"/> <mass value="${plateMass}"/> <inertia ixx="0.001401" ixy="0.0" ixz="0.0"
  iyy="0.000723" iyz="-0.0" izz="0.002122"/> </inertial> </link> <!-- BASE -->






  <!--link name="end_effector">
    <inertial>
      <origin xyz="0 0 1.0945" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="13410" ixy="0.0" ixz="0.0" iyy="13850" iyz="0.0" izz="27150"/>
    </inertial>
    <visual>
      <origin xyz="0 0 ${(plateHeight+baseHeight+sidePlateHeight+motor2Length+motor3Length)/4+excavatorHeight/4}" rpy="0 0 0"/>
      <geometry>
        <box size="${excavatorLenght} ${excavatorWidth} ${excavatorHeight}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${(plateHeight+baseHeight+sidePlateHeight+motor2Length+motor3Length)/4+excavatorHeight/4}" rpy="0 0 0"/>
      <geometry>
        <box size="${excavatorLenght} ${excavatorWidth} ${excavatorHeight}"/>
      </geometry>
    </collision>

  </link>

  <joint name="motor3_end_effector_joint" type="revolute">
    <parent link="motor3"/>
    <child link="end_effector"/>
    <axis xyz=" 0 1 0"/>
    <origin xyz="0 0 ${(plateHeight+baseHeight+sidePlateHeight+motor2Length+motor3Length)/4+excavatorHeight/4}" rpy="0 0 0"/>
    <dynamics damping="${sidePlate2Motor2Damping}"/>
    <limit effort="100.0" velocity="0.5" lower="-1.571" upper="1.571"/>
  </joint>

  <gazebo>
    <plugin filename="libgazebo_ros_control.so" name="control"/>
  </gazebo-->

</robot>
