<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="wheel" params="lr tY tX">
    <link name="${lr}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}"/> <!-- Diffrence-->
        <geometry>
          <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}"/>
        <geometry>
          <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
        </geometry>
      </collision>

      <xacro:default_inertial mass="${wheelMass}"/>
    </link>

    <joint name="${lr}_wheel_joint" type="continuous">
      <axis xyz="0 1 0" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="${lr}_wheel"/>
      <origin xyz="${(wheelPos*tX)} ${tY*wheelWidth/2+tY*chassisWidth/2} ${wheelDrop}" rpy="0 0 0"/>
    </joint>

    <gazebo reference="${lr}_wheel">
      <mu1 value="200"/>
      <mu2 value="100"/>
      <kp value="10000000.0"/>
      <kd value="1.0"/>
      <!-- <! <fdir1 value="1 0 0"/> -> -->
      <material>Gazebo/Black</material>
    </gazebo>

    <transmission name="${lr}_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <actuator name="${lr}_Motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
      <joint name="${lr}_wheel_joint">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
    </transmission>
  </xacro:macro>

  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0" iyy="${m*(3*r*r+h*h)/12}" iyz="0" izz="${m*r*r/2}"/>
  </xacro:macro>

  <xacro:macro name="box_inertia" params="m x y z">
    <inertia ixx="${m*(y*y+z*z)/12}" ixy="0" ixz="0" iyy="${m*(x*x+z*z)/12}" iyz="0" izz="${m*(x*x+z*z)/12}"/>
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
    <inertia ixx="${2*m*r*r/5}" ixy="0" ixz="0" iyy="${2*m*r*r/5}" iyz="0" izz="${2*m*r*r/5}"/>
  </xacro:macro>

</robot>
